FROM rust:1.70.0

WORKDIR /usr/src/

RUN apt-get update \
    && apt-get install -y cmake
RUN git clone https://github.com/landaudiogo/cc-assignment-2023 \
    && cd cc-assignment-2023 \
    && cargo install --path experiment-producer

WORKDIR /usr/src/cc-assignment-2023

ADD auth/group5/ cc-assignment-2023/experiment-producer/auth

ENTRYPOINT ["experiment-producer", "--brokers", "13.49.128.80:19093,13.49.128.80:29093,13.49.128.80:39093"]
