version: "3.5"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    extra_hosts:
      - host.docker.internal:host-gateway
    ports: 
      - 3008:9090

  grafana: 
    image: grafana/grafana-enterprise
    ports: 
      - 3009:3000
    volumes: 
      - grafana-storage:/var/lib/grafana

volumes:
  prometheus-data:
  grafana-storage: