FROM python:3.8

RUN apt-get clean \
    && apt-get -y update

RUN apt-get -y install \
    nginx \
    python3-dev \
    build-essential

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY ./app.py .
EXPOSE 3003
ENV FLASK_APP=app.py
CMD [ "flask","run", "--host", "0.0.0.0" ]