apiVersion: v1
kind: Service
metadata:
  name: prometheus-service-ext
spec:
  type: NodePort
  selector:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: prometheus
      app.kubernetes.io/name: prometheus
  ports:
    - port: 80
      targetPort: 9090
      nodePort: 30900