apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: experiment-consumer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: experiment-consumer
  maxReplicas: 8
  minReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 60
        type: Utilization
    type: Resource